### ISSUE TITLE
Continue working on this

### ISSUE THREAD

**Issue by Hannibal42** [kiliankoe/mitbewohnervereinbarung#1]
We still need that agreement!

**Comment by heisig** [comment]
Still waiting :D

**Comment by kiliankoe** [comment]
Invited @sjmielke and @justusadam, maybe they want to add some stuff 😄

**Comment by JustusAdam** [comment]
Why @sjmielke? He doesn't even live here anymore... (neither @kiliankoe btw)

**Comment by kiliankoe** [comment]
That doesn't feel like a reason for not having opinions 😉

**Comment by JustusAdam** [comment]
Are you serious? Do you want me to make some proposals as to how you should live in your flat? Is that also an appropriate place to "have opinions"?

**Comment by kiliankoe** [comment]
Oh come on, as if this is a serious and legally binding document to abide by. Lost your sense of humor during the move? 😜

**Comment by Feliix42** [comment]
Is this going to be finished anytime soon? :D

**Comment by kiliankoe** [comment]
I bet @JustusAdam will get on it once he moves out and finds an "appropriate place to "have opinions"" 😄

**Comment by JustusAdam** [comment]
Closed due to inactivity!
